# Generated by Django 4.2.19 on 2025-02-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="repassword",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
