# Generated by Django 4.2.19 on 2025-02-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_repassword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="repassword",
        ),
    ]
