# Generated by Django 4.2.19 on 2025-02-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_event_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_name",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
