# Generated by Django 4.2.19 on 2025-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_event_description_alter_event_event_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisteredStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                (
                    "last_name",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                ("email", models.EmailField(max_length=100, unique=True)),
                (
                    "phone_number",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                ("enrolled_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
