# Generated by Django 4.2.19 on 2025-02-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_registeredstudent_event_registeredstudent_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeredstudent",
            name="enrolled_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
