# Generated by Django 4.2.19 on 2025-03-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_registeredstudent_event_registeredstudent_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeredstudent",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
